### ISSUE TITLE
Statuses and resources should have models

### ISSUE THREAD

**Issue by NimaBoscarino** [jmatsuba/covid-updates#3]
The briefings and resources are currently hardcoded in the view. To allow for CRUD actions, these should be stored in a database, and they should both have appropriate models. Their respective views should be updated accordingly.

**Comment by jmatsuba** [comment]
Related also create categories.

`national_updates.last(3)` is a call i'd like to be able to make in the view for example on the home page

On the resources side.

I want to break this down into categories... 

so `tools` `science` `government programs` etc should be the categories and be able to go `tools.resources` in the view
